# Generated by Django 5.2.10 on 2026-01-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('LIVE', 'Live'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10),
        ),
    ]
