# Generated by Django 5.2.10 on 2026-01-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Duration of exam in minutes'),
            preserve_default=False,
        ),
    ]
