# Generated by Django 5.2.10 on 2026-01-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_exam_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='setquestion',
            name='correct_option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
